name: Sempgrep

on: [push]

jobs:
  semgrep:
    # User-definable name of this GitHub Actions job:
    name: semgrep/ci 
    # If you are self-hosting, change the following `runs-on` value: 
    runs-on: ubuntu-latest

    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: returntocorp/semgrep

    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: Run Sempgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: 'p/your-rule-pack'
          pattern: 'your-pattern'
          output-file: semgrep.log

      - name: Save semgrep results
        run: |
          cat semgrep.log
          echo "Semgrep Results" > results.log
          echo "---------------------" >> results.log
          cat semgrep.log >> results.log
          echo "---------------------" >> results.log
          echo "End of Semgrep Results" >> results.log

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: semgrep-results
          path: results.log
